#!/bin/sh

ARCH="$(uname -s)"

export LANG=fr_FR.UTF-8

which vim >/dev/null 2>&1
if [ $? -eq 0 ]; then 
  export EDITOR=vim
fi

which most >/dev/null 2>&1
if [ $? -eq 0 ]; then 
  export PAGER=most
fi

########
# PATH #
########
PATH="/bin:/sbin:$PATH"

if [ -d ~/bin/ ]
then 
  PATH="$HOME/bin:$HOME/sbin:$PATH"
fi

if [ -d ~/local/ ]
then 
  PATH="$HOME/local/bin:$HOME/local/sbin:$PATH"
fi

if [ -d ~/.local/ ]
then 
  PATH="$HOME/.local/bin:$HOME/.local/sbin:$PATH"
fi

if [ -d /usr/local/ ]
then 
  PATH="/usr/local/bin:/usr/local/sbin:$PATH"
fi

export PATH
###############################

export LS_COLORS='no=00:fi=00:di=0;33:ln=01;36:pi=40;33:so=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jpg=01;35:*.gif=01;35:*.bmp=01;35:*.pgm=01;35:*.pbm=01;35:*.ppm=01;35:*.tga=01;35:*.png=01;35:*.GIF=01;35:*.JPG=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.mpg=01;37:*.avi=01;37:*.gl=01;37:*.dl=01;37:*.cc=01;37:*.c=01;37:*.hh=01;37:*.h=01;37:*Makefile=4;32:*.pl=4;32:*.sh=4;32'
export LSCOLORS="dxGxbxhxCxDxDxhbhbacad"

alias vrac=~/web/vrac/vrac.sh

